#include <ButtonConstants.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <GUIListBox.au3>
#include <WindowsConstants.au3>
Opt("GUIOnEventMode", 1)
#Region ### START Koda GUI section ### Form=SSLink.kxf
Global $SSLinker = GUICreate("SSLinker                                                                                                                         code by qokelate[udf.q@qq.com]", 1029, 516, 202, 137)
GUISetFont(11, 400, 0, "ÐÂËÎÌå")
GUISetOnEvent($GUI_EVENT_CLOSE, "SSLinkerClose")
GUISetOnEvent($GUI_EVENT_MINIMIZE, "SSLinkerMinimize")
GUISetOnEvent($GUI_EVENT_MAXIMIZE, "SSLinkerMaximize")
GUISetOnEvent($GUI_EVENT_RESTORE, "SSLinkerRestore")
Global $Group1 = GUICtrlCreateGroup("login info", 20, 10, 215, 185)
Global $i_user = GUICtrlCreateInput("username", 40, 30, 181, 23, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetOnEvent(-1, "i_userChange")
Global $i_password = GUICtrlCreateInput("password", 40, 70, 181, 23, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_PASSWORD))
GUICtrlSetOnEvent(-1, "i_passwordChange")
Global $b_login = GUICtrlCreateButton("login", 120, 151, 105, 35)
GUICtrlSetOnEvent(-1, "b_loginClick")
Global $c_remember = GUICtrlCreateCheckbox("remember me", 70, 120, 137, 17)
GUICtrlSetOnEvent(-1, "c_rememberClick")
Global $b_register = GUICtrlCreateButton("register", 27, 151, 90, 35)
GUICtrlSetOnEvent(-1, "b_registerClick")
GUICtrlCreateGroup("", -99, -99, 1, 1)
Global $Group2 = GUICtrlCreateGroup("service info", 20, 270, 215, 225)
Global $i_listenHost = GUICtrlCreateInput("listen host", 40, 300, 181, 23, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetOnEvent(-1, "i_listenHostChange")
Global $i_listenPort = GUICtrlCreateInput("listen port", 40, 327, 181, 23, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetOnEvent(-1, "i_listenPortChange")
Global $i_serverHost = GUICtrlCreateInput("server host", 40, 354, 181, 23, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY))
GUICtrlSetOnEvent(-1, "i_serverHostChange")
Global $i_serverPort = GUICtrlCreateInput("server port", 40, 382, 181, 23, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY))
GUICtrlSetOnEvent(-1, "i_serverPortChange")
Global $i_serverPassword = GUICtrlCreateInput("password", 40, 409, 181, 23, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY))
GUICtrlSetOnEvent(-1, "i_serverPasswordChange")
Global $i_method = GUICtrlCreateInput("server method", 40, 436, 181, 23, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY))
GUICtrlSetOnEvent(-1, "i_methodChange")
Global $i_expireTime = GUICtrlCreateInput("expire time", 39, 462, 181, 23, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY))
GUICtrlSetOnEvent(-1, "i_expireTimeChange")
GUICtrlCreateGroup("", -99, -99, 1, 1)
Global $Group3 = GUICtrlCreateGroup("buy list", 240, 10, 375, 485)
Global $l_buyList = GUICtrlCreateList("", 260, 90, 340, 381, BitOR($LBS_NOTIFY,$WS_VSCROLL,$WS_BORDER))
GUICtrlSetOnEvent(-1, "l_buyListClick")
Global $b_freshBuy = GUICtrlCreateButton("fresh", 270, 40, 75, 35)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetOnEvent(-1, "b_freshBuyClick")
Global $b_buy = GUICtrlCreateButton("buy", 378, 40, 75, 35)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetOnEvent(-1, "b_buyClick")
GUICtrlCreateGroup("", -99, -99, 1, 1)
Global $Group4 = GUICtrlCreateGroup("server list", 640, 10, 375, 485)
Global $l_myList = GUICtrlCreateList("", 660, 110, 340, 366, BitOR($LBS_NOTIFY,$WS_VSCROLL,$WS_BORDER))
GUICtrlSetOnEvent(-1, "l_myListClick")
Global $b_freshList = GUICtrlCreateButton("fresh", 670, 50, 75, 35)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetOnEvent(-1, "b_freshListClick")
Global $b_selected = GUICtrlCreateButton("use", 761, 50, 75, 35)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetOnEvent(-1, "b_selectedClick")
Global $b_test = GUICtrlCreateButton("use && test", 863, 70, 135, 35)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetOnEvent(-1, "b_testClick")
Global $b_createHosting = GUICtrlCreateButton("create hosting", 863, 28, 135, 35)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetOnEvent(-1, "b_createHostingClick")
GUICtrlCreateGroup("", -99, -99, 1, 1)
Global $Group5 = GUICtrlCreateGroup("follow me", 20, 200, 215, 65)
Global $b_donate = GUICtrlCreateButton("donate", 28, 221, 90, 35)
GUICtrlSetOnEvent(-1, "b_donateClick")
Global $b_about = GUICtrlCreateButton("about", 121, 221, 105, 35)
GUICtrlSetOnEvent(-1, "b_aboutClick")
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUISetState(@SW_SHOW)
#EndRegion ### END Koda GUI section ###

